server.port.http=8080
server.port=8443

server.ssl.key-store=classpath:clos21.kr.p12
server.ssl.key-store-password=Asp53469
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=clos21.kr

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://222.122.203.82:3306/apiMain
spring.datasource.username=api
spring.datasource.password=upsung53469

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show-sql=true
logging.level.org.hibernate.type.descriptor.sql=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.main.allow-bean-definition-overriding=true

server.forward-headers-strategy=native